package com.quanlian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telphone
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Long telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.chinese
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Double chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.english
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Double english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.math
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private Double math;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telphone
     *
     * @return the value of student.telphone
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Long getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telphone
     *
     * @param telphone the value for student.telphone
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setTelphone(Long telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_name
     *
     * @return the value of student.class_name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_name
     *
     * @param className the value for student.class_name
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.chinese
     *
     * @return the value of student.chinese
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Double getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.chinese
     *
     * @param chinese the value for student.chinese
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setChinese(Double chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.english
     *
     * @return the value of student.english
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Double getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.english
     *
     * @param english the value for student.english
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setEnglish(Double english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.math
     *
     * @return the value of student.math
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public Double getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.math
     *
     * @param math the value for student.math
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    public void setMath(Double math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat Jun 02 09:41:33 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", telphone=").append(telphone);
        sb.append(", className=").append(className);
        sb.append(", chinese=").append(chinese);
        sb.append(", english=").append(english);
        sb.append(", math=").append(math);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}